# Generated by Django 5.0.6 on 2024-06-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_container_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
